name: Blender Render CI

on:
  push:
    branches: [ master ]
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Blender
      run: |
        wget https://download.blender.org/release/Blender2.83/blender-2.83.4-linux64.tar.xz
        tar xf blender-2.83.4-linux64.tar.xz
        ./blender-2.83.4-linux64/blender -b *.blend -o ./output -F PNG -f 1
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Output
        path: ./output.*
